"""Ajout coefficient et credits à Cours

Revision ID: 06483a1901d5
Revises: 
Create Date: 2025-06-05 18:44:13.132447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06483a1901d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coefficient', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.drop_column('credits')
        batch_op.drop_column('coefficient')

    # ### end Alembic commands ###
