"""Ajout du champ durée sur les séances

Revision ID: 7af0ae72b45e
Revises: 06483a1901d5
Create Date: 2025-06-07 00:44:37.205137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af0ae72b45e'
down_revision = '06483a1901d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cours_nom', ['nom'])

    with op.batch_alter_table('seance', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('cours_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('heure_debut')
        batch_op.drop_column('heure_fin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure_fin', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('heure_debut', sa.TIME(), nullable=False))
        batch_op.alter_column('cours_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
