"""Base propre avec durée

Revision ID: 8faa643a43e3
Revises: 7af0ae72b45e
Create Date: 2025-06-07 01:27:13.211257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8faa643a43e3'
down_revision = '7af0ae72b45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duree', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seance', schema=None) as batch_op:
        batch_op.drop_column('duree')

    # ### end Alembic commands ###
